declare const styles: {
    dashboardComponent: string;
    refreshInfo: string;
    refreshButton: string;
    messagesContainer: string;
    messagesHeader: string;
    messageStats: string;
    messagesList: string;
    messageCard: string;
    unreadMessage: string;
    readMessage: string;
    messageHeader: string;
    messageTitle: string;
    priorityIndicator: string;
    messageMetadata: string;
    priority: string;
    date: string;
    messageContent: string;
    messageFooter: string;
    messageInfo: string;
    markReadButton: string;
    readIndicator: string;
    loading: string;
    spinner: string;
    spin: string;
    error: string;
    errorIcon: string;
    noMessages: string;
    noMessagesIcon: string;
    placeholder: string;
    placeholderIcon: string;
    placeholderTitle: string;
    placeholderDescription: string;
    configureButton: string;
};
export default styles;
//# sourceMappingURL=DashboardComponent.module.scss.d.ts.map